//==========================================================================
//
//  Notice:      This file is automatically generated.
//               Please don't modify this file.
//
//==========================================================================

//Reference:

using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Linq;
using System.Diagnostics;
using System.Data;
using Krustallos;
using Database.Database;
using Boolean = System.Boolean;
using String = System.String;
using Type = System.Type;
using Int = System.Int32;
using Real = System.Double;
using Byte = System.Byte;

namespace Database.Krustallos
{
    public class KrustallosData
    {
        public VersionedStore<ImmutableSortedDictionary<Int, TestRecord>> TestRecordBySessionIndex = new VersionedStore<ImmutableSortedDictionary<Int, TestRecord>>(() => new ImmutableSortedDictionary<Int, TestRecord>());
        public VersionedStore<ImmutableSortedDictionary<Int, TestLockRecord>> TestLockRecordById = new VersionedStore<ImmutableSortedDictionary<Int, TestLockRecord>>(() => new ImmutableSortedDictionary<Int, TestLockRecord>());
        public VersionedStore<ImmutableSortedDictionary<Int, TestDuplicatedKeyNameRecord>> TestDuplicatedKeyNameRecordById = new VersionedStore<ImmutableSortedDictionary<Int, TestDuplicatedKeyNameRecord>>(() => new ImmutableSortedDictionary<Int, TestDuplicatedKeyNameRecord>());
        public VersionedStore<ImmutableSortedDictionary<String, ImmutableSortedDictionary<Int, TestDuplicatedKeyNameRecord>>> TestDuplicatedKeyNameRecordByAAndB = new VersionedStore<ImmutableSortedDictionary<String, ImmutableSortedDictionary<Int, TestDuplicatedKeyNameRecord>>>(() => new ImmutableSortedDictionary<String, ImmutableSortedDictionary<Int, TestDuplicatedKeyNameRecord>>());
    }

    public partial class KrustallosDataAccess : IDataAccess
    {
        private Instance Instance;
        private KrustallosData Data;
        private Transaction Transaction;
        private ITransactionLock TransactionLock;
        public KrustallosDataAccess(Instance Instance, KrustallosData Data, IsolationLevel IsolationLevel, ITransactionLock TransactionLock)
        {
            this.Instance = Instance;
            this.Data = Data;
            this.Transaction = new Transaction(Instance, IsolationLevel);
            this.TransactionLock = TransactionLock;
        }
        public KrustallosDataAccess(Instance Instance, KrustallosData Data, IsolationLevel IsolationLevel, Func<Transaction, ITransactionLock> TransactionLockFactory)
        {
            this.Instance = Instance;
            this.Data = Data;
            this.Transaction = new Transaction(Instance, IsolationLevel);
            this.TransactionLock = TransactionLockFactory(Transaction);
        }

        public void Dispose()
        {
            if (Transaction != null)
            {
                Transaction.Revert();
                Transaction.Dispose();
                Transaction = null;
            }
            if (TransactionLock != null)
            {
                TransactionLock.ExitAll();
                TransactionLock = null;
            }
        }

        public void Complete()
        {
            if (Transaction != null)
            {
                Transaction.Commit();
                Transaction.Dispose();
                Transaction = null;
            }
            else
            {
                throw new InvalidOperationException();
            }
            if (TransactionLock != null)
            {
                TransactionLock.ExitAll();
                TransactionLock = null;
            }
            else
            {
                throw new InvalidOperationException();
            }
        }
    }

    public partial class KrustallosDataAccess
    {
        private static TestRecord Clone(TestRecord v)
        {
            var nv = new TestRecord();
            nv.SessionIndex = v.SessionIndex;
            nv.Value = v.Value;
            return nv;
        }
        private static TestLockRecord Clone(TestLockRecord v)
        {
            var nv = new TestLockRecord();
            nv.Id = v.Id;
            nv.Value = v.Value;
            return nv;
        }
        private static TestDuplicatedKeyNameRecord Clone(TestDuplicatedKeyNameRecord v)
        {
            var nv = new TestDuplicatedKeyNameRecord();
            nv.Id = v.Id;
            nv.A = v.A;
            nv.B = v.B;
            return nv;
        }
    }

    public partial class KrustallosDataAccess
    {
        public void FromTestRecordUpsertOne(TestRecord v)
        {
            Transaction.UpdateVersioned(new String[] { "TestRecord", "SessionIndex" }, this.Data.TestRecordBySessionIndex, _d_ => _d_.AddOrSetItem(v.SessionIndex, v));
        }

        public Optional<TestRecord> FromTestRecordSelectOptionalBySessionIndex(Int SessionIndex)
        {
            var _l_ = Transaction.CheckReaderVersioned(this.Data.TestRecordBySessionIndex, _d_ => _d_.Range(SessionIndex, SessionIndex).Select(_p_ => _p_.Value).Select(_e_ => Clone(_e_))).ToList();
            if (_l_.Count == 0) { return null; }
            if (_l_.Count > 1)
            {
                throw new InvalidOperationException("MultipleValueFor: (" + String.Join(" ", (new Object[] { SessionIndex }).Select(o => o.ToString()).ToArray()) + ")");
            }
            return _l_.Single();
        }

        public void FromTestLockRecordUpsertOne(TestLockRecord v)
        {
            Transaction.UpdateVersioned(new String[] { "TestLockRecord", "Id" }, this.Data.TestLockRecordById, _d_ => _d_.AddOrSetItem(v.Id, v));
        }

        public void FromTestLockRecordDeleteOptionalById(Int Id)
        {
            Transaction.UpdateVersioned(new String[] { "TestLockRecord", "Id" }, this.Data.TestLockRecordById, _d_ => _d_.RemoveIfExist(Id));
        }

        public Optional<TestLockRecord> FromTestLockRecordSelectOptionalById(Int Id)
        {
            var _l_ = Transaction.CheckReaderVersioned(this.Data.TestLockRecordById, _d_ => _d_.Range(Id, Id).Select(_p_ => _p_.Value).Select(_e_ => Clone(_e_))).ToList();
            if (_l_.Count == 0) { return null; }
            if (_l_.Count > 1)
            {
                throw new InvalidOperationException("MultipleValueFor: (" + String.Join(" ", (new Object[] { Id }).Select(o => o.ToString()).ToArray()) + ")");
            }
            return _l_.Single();
        }

        public Optional<TestLockRecord> FromTestLockRecordLockOptionalById(Int Id)
        {
            if (TransactionLock != null) { TransactionLock.Enter(new Object[] { "TestLockRecord", "Id", Id }); }
            var _l_ = Transaction.CheckCurrentVersioned(this.Data.TestLockRecordById, _d_ => _d_.Range(Id, Id).Select(_p_ => _p_.Value).Select(_e_ => Clone(_e_))).ToList();
            if (_l_.Count == 0) { return null; }
            if (_l_.Count > 1)
            {
                throw new InvalidOperationException("MultipleValueFor: (" + String.Join(" ", (new Object[] { Id }).Select(o => o.ToString()).ToArray()) + ")");
            }
            return _l_.Single();
        }

        public Optional<TestDuplicatedKeyNameRecord> FromTestDuplicatedKeyNameRecordSelectOptionalByA(String A)
        {
            var _l_ = Transaction.CheckReaderVersioned(this.Data.TestDuplicatedKeyNameRecordByAAndB, _d_ => _d_.Range(A, A).Select(_p_ => _p_.Value).SelectMany(_e_ => _e_).Select(_p_ => _p_.Value).Select(_e_ => Clone(_e_))).ToList();
            if (_l_.Count == 0) { return null; }
            if (_l_.Count > 1)
            {
                throw new InvalidOperationException("MultipleValueFor: (" + String.Join(" ", (new Object[] { A }).Select(o => o.ToString()).ToArray()) + ")");
            }
            return _l_.Single();
        }

        public Optional<TestDuplicatedKeyNameRecord> FromTestDuplicatedKeyNameRecordSelectOptionalByAAndB(String A, Int B)
        {
            var _l_ = Transaction.CheckReaderVersioned(this.Data.TestDuplicatedKeyNameRecordByAAndB, _d_ => _d_.Range(A, A).Select(_p_ => _p_.Value).SelectMany(_e_ => _e_.Range(B, B)).Select(_p_ => _p_.Value).Select(_e_ => Clone(_e_))).ToList();
            if (_l_.Count == 0) { return null; }
            if (_l_.Count > 1)
            {
                throw new InvalidOperationException("MultipleValueFor: (" + String.Join(" ", (new Object[] { A, B }).Select(o => o.ToString()).ToArray()) + ")");
            }
            return _l_.Single();
        }

        public List<TestDuplicatedKeyNameRecord> FromTestDuplicatedKeyNameRecordSelectRangeByAOrderByAAndBDesc(String A, Int _Skip_, Int _Take_)
        {
            return Transaction.CheckReaderVersioned(this.Data.TestDuplicatedKeyNameRecordByAAndB, _d_ => _d_.Range(A, A).Select(_p_ => _p_.Value).SelectMany(_e_ => _e_).Select(_p_ => _p_.Value).OrderBy(_e_ => _e_.A).ThenByDescending(_e_ => _e_.B).Skip(_Skip_).Take(_Take_).Select(_e_ => Clone(_e_))).ToList();
        }

        public void FromTestDuplicatedKeyNameRecordInsertOne(TestDuplicatedKeyNameRecord v)
        {
            var _v_ = Clone(v);
            Transaction.UpdateVersioned(new String[] { "TestDuplicatedKeyNameRecord", "Id" }, this.Data.TestDuplicatedKeyNameRecordById, _d_ => _d_.Add(v.Id, _v_));
            Transaction.UpdateVersioned(new String[] { "TestDuplicatedKeyNameRecord", "A", "B" }, this.Data.TestDuplicatedKeyNameRecordByAAndB, _d_ => _d_.AddOrSetItem(v.A, _d_.GetOrCreate(v.A, () => new ImmutableSortedDictionary<Int, TestDuplicatedKeyNameRecord>()).Add(v.B, _v_)));
        }

        public void FromTestDuplicatedKeyNameRecordUpdateOptional(TestDuplicatedKeyNameRecord v)
        {
            var _v_ = Clone(v);
            Transaction.UpdateVersioned(new String[] { "TestDuplicatedKeyNameRecord", "Id" }, this.Data.TestDuplicatedKeyNameRecordById, _d_ => _d_.SetItemIfExist(v.Id, _v_));
            Transaction.UpdateVersioned(new String[] { "TestDuplicatedKeyNameRecord", "A", "B" }, this.Data.TestDuplicatedKeyNameRecordByAAndB, _d_ => _d_.AddOrSetItem(v.A, _d_.GetOrCreate(v.A, () => new ImmutableSortedDictionary<Int, TestDuplicatedKeyNameRecord>()).SetItemIfExist(v.B, _v_)));
        }
    }

    public class KrustallosDataAccessPool
    {
        public UInt64 Hash
        {
            get
            {
                return 0xCF3EA48842165733;
            }
        }

        private static ConcurrentDictionary<String, KeyValuePair<Instance, KrustallosData>> Instances = new ConcurrentDictionary<String, KeyValuePair<Instance, KrustallosData>>();

        public IDataAccess Create(String ConnectionString)
        {
            return Create(ConnectionString, IsolationLevel.ReadCommitted, (ITransactionLock)(null));
        }
        public IDataAccess Create(String ConnectionString, ITransactionLock TransactionLock)
        {
            return Create(ConnectionString, IsolationLevel.ReadCommitted, TransactionLock);
        }
        public IDataAccess Create(String ConnectionString, IsolationLevel IsolationLevel)
        {
            return Create(ConnectionString, IsolationLevel, (ITransactionLock)(null));
        }
        public IDataAccess Create(String ConnectionString, IsolationLevel IsolationLevel, ITransactionLock TransactionLock)
        {
            return Create(ConnectionString, IsolationLevel, t => TransactionLock);
        }
        public IDataAccess Create(String ConnectionString, IsolationLevel IsolationLevel, Func<Transaction, ITransactionLock> TransactionLockFactory)
        {
            var Pair = Instances.GetOrAdd(ConnectionString, Key => new KeyValuePair<Instance, KrustallosData>(new Instance(), new KrustallosData()));
            return new KrustallosDataAccess(Pair.Key, Pair.Value, IsolationLevel, TransactionLockFactory);
        }
    }
}
